### ISSUE TITLE
Request for Missing File in Code

### ISSUE THREAD

**Issue by HYLPRC** [ychuest/MRLHGNN#1]
Dear Author,

I hope this message finds you well. Your work in the field of drug repositioning is highly impactful, and I am currently attempting to replicate and compare your results with my own research. However, I have encountered an issue due to a missing file in your code, specifically drug_disease = np.load('./base_meta_path/drug--disease.npy'). I would greatly appreciate it if you could provide this file or update the repository with the necessary data to facilitate replication.

Thank you very much for your assistance and for your valuable contributions to the field.

Best regards

**Comment by ychuest** [comment]
Hi~, nice to hear from you. The relevant part of the dataset can be obtained by adding my wechat. WeChat number: 17352645165.
